### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by alice-cool** [AtsuMiyai/UPD#2]
![image](https://github.com/AtsuMiyai/UPD/assets/16870890/484efce4-eee2-4b1d-8856-e349953dde35)
UPD-main/scripts/convert_mmbench_for_submission.py", line 5, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'

Could you tell me the datasets folder download link?

**Comment by AtsuMiyai** [comment]
@alice-cool 
Thanks for your interest!
Could you please run `pip install datasets==2.18.0` following pyproject.toml?

Thank you!

**Comment by alice-cool** [comment]
Hello ，can you give me some suggestions about this error? Hope for your reply.



---Original---
From: "Atsuyuki ***@***.***&gt;
Date: Tue, Jul 2, 2024 10:33 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [AtsuMiyai/UPD] ModuleNotFoundError: No module named 'datasets'(Issue #2)




 
@alice-cool
 Thanks for your interest!
 Could you please run pip install datasets==2.18.0 following pyproject.toml?
 
Thank you!

**Comment by AtsuMiyai** [comment]
@alice-cool 
Hello! 

I think you do not install `datasets` module. 
Could you try `pip install datasets==2.18.0`?

**Comment by alice-cool** [comment]
I want to ask about the following picture. I may fail to send it in the previous dialogue. Could you give me some suggestions? Thanks for your quick reply. Hope for your suggestions.
![image](https://github.com/AtsuMiyai/UPD/assets/16870890/fceb366e-b4a7-439d-bd30-4c38394ccc64)

**Comment by AtsuMiyai** [comment]
@alice-cool 
Oh, thanks for your point! 


After merging the pull request and updating transformers version, an error occurred due to a change in the transformers' specifications.

Could you add `inputs.pop("cache_position")` following https://github.com/AtsuMiyai/UPD/commit/8fac80d1399fbb6bb566e95d8d195f64aaf30928

**Comment by alice-cool** [comment]
> @alice-cool Oh, thanks for your point!
> 
> After merging the pull request and updating transformers version, an error occurred due to a change in the transformers' specifications.
> 
> Could you add `inputs.pop("cache_position")` following [8fac80d](https://github.com/AtsuMiyai/UPD/commit/8fac80d1399fbb6bb566e95d8d195f64aaf30928)

Thank you four your reply. It works well.

**Comment by alice-cool** [comment]
Hello I use lava13b to get the  prediction results. So I use Evaluation section to evaluate my prediction accuracy rate. But I got the error to input the Openai key. But I don't have Openai key, and I use the llava (which doesn't need API key.) So how can I evaluate my lava13b prediction results? Hope for your reply.
![image](https://github.com/AtsuMiyai/UPD/assets/16870890/1c2cc390-5be4-4bc5-8086-d61fec297d85)
![image](https://github.com/AtsuMiyai/UPD/assets/16870890/bf83f241-cb6b-43c6-bb18-bd707d0fbbe8)

**Comment by AtsuMiyai** [comment]
Yes, you need to register openai_api_key for the evaluation! 
Please refer to the requirements section!
